### ISSUE TITLE
依赖的库无法下载

### ISSUE THREAD

**Issue by ChangDonglei** [callmefeifei/baby-names#17]
sudo pip install -i http://pypi.douban.com/simple/ --trusted-host=pypi.douban.com -r docs/requirements.txt
提示找不到
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'

**Comment by fivezh** [comment]
进入到项目目录下，是可以安装的

我依赖安装完成后，跑起来了

**Comment by ChangDonglei** [comment]
我这边还是报错，子进程没有运行成功，不是pip的错。
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-_9m_m4g6/cjklib_657c54d10fae425ebcaf12b2d34cfbf3/setup.py", line 4, in <module>
          from ez_setup import use_setuptools
        File "/private/tmp/pip-install-_9m_m4g6/cjklib_657c54d10fae425ebcaf12b2d34cfbf3/ez_setup.py", line 106
          except pkg_resources.VersionConflict, e:
                                              ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by fivezh** [comment]
python版本是多少？pip install 环节我之前也报错，多次执行后成功的

另外，我现在执行后有死循环，也没法产出结果，还在调试代码，看代码都是2年前的，不确定是否还能用

更新：看了下代码逻辑，依赖服务有部分已经不可用，代码逻辑就会出现大量过滤空转的情况，需要手动注释些代码

**Comment by elicicli** [comment]
请问怎么安装依赖库啊？提示找不到文件

**Comment by denzhengwei** [comment]
> python版本是多少？pip install 环节我之前也报错，多次执行后成功的
> 
> 另外，我现在执行后有死循环，也没法产出结果，还在调试代码，看代码都是2年前的，不确定是否还能用
> 
> 更新：看了下代码逻辑，依赖服务有部分已经不可用，代码逻辑就会出现大量过滤空转的情况，需要手动注释些代码

老哥有修复可用版本么？我还在爬依赖的坑，方便的话发一份用用251314770@qq.com
